multirotor:
    cf: 5.5e-5
    cm: 6.0e-6
    max_thrust: 5
    min_thrust: 0
    rotors:
        -   x:  0.13
            y: -0.22
            z: -1.0

        -   x: 0.13
            y: 0.22
            z: 1.0

        -   x: -0.13
            y: 0.2
            z: -1.0

        -   x: -0.13
            y: -0.2
            z: 1.0

