multirotor:
    cf: 1.373e-5
    cm: 2.523e-7
    max_thrust: 5.0
    min_thrust: 0.1
    rotors:
        -   x:  0.13
            y: -0.22
            z: -1.0

        -   x: 0.13
            y: 0.22
            z: 1.0

        -   x: -0.13
            y: 0.2
            z: -1.0

        -   x: -0.13
            y: -0.2
            z: 1.0

